spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #basedir:
          uri: https://github.com/xiongyongjie/springcloudproject.git
          search-paths: config/dev
          default-label: master
          username: xiongyongjie
          password: xyj126com
      #设置分支
      label: master
      #当前激活的文件
      profile: dev
server:
  port: 8888