eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:7777/eureka/
  instance:
    #eureka显示为IP:PORT 格式配置
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
#rabbitmq 配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #消息总线配置
  cloud:
     bus:
       trace:
         enabled: true
       enabled: true

management:
  endpoint:
    bus-refresh:
      enabled: true
app:
  ver: 3000.001